defaults:
  - base_model: dualcnntd3
  - clearml: clearml
  - sim: dual_sim
action_dim: 2  # number of actions produced by the model
max_action: 1  # maximum absolute value of output actions
nr_eval_episodes: 1000  # how many episodes to use to run evaluation
device: cuda
task_name: 'dual_eval_training'

save_directory: robot_nav/models/dualCNNTD3/checkpoint
load_checkpoint: true
checkpoint: rl__checkpoint_330432.pt

save_every: 5  # save the model every n training cycles